# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bond sensitivities
#' 
#' @param x bond details as matrix
#' @param stepSize sensitivities stepsize
rcppPortParallel <- function(x, stepSize) {
    .Call('_RTLappBonds_rcppPortParallel', PACKAGE = 'RTLappBonds', x, stepSize)
}

